name: Push translations to Mojito

on:
  push
  # push:
  #   branches:
  #     - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8.0.292
      - name: Install Mojito
        run: source <(curl -L -N -s https://mojito.pinadmin.com/cli/install.sh)
      - name: Push new strings to Mojito
        run: mojito push -r woocommerce -s /locale -ft PO
